### PR TITLE
fix: get_block_by_number endpoint

### LINKED ISSUE #270: Hive Testing: `eth_getBlockByNumber`
- [ ]   get-block-n
- [ ]   get-block-notfound
- [ ]   get-finalized
- [ ]   get-genesis
- [ ]   get-latest
- [ ]   get-safe

### PR DESCRIPTION
**Pull request by avilagaston9**
**Motivation**

The `get-finalized` and `get-safe` endpoints were returning null values because we weren't handling the forkchoice updates from the engine.

**Description**

This PR adds a minimal implementation to store forkchoice updates and pass the tests. Additionally, it takes the opportunity to implement a refactor.

- Moves `core/types/engine/payload.rs` to `rpc/types/payload.rs`.
- Creates `rpc/engine/payload.rs` and `rpc/engine/fork_choice.rs` to modularize `rpc/engine/mod.rs`.
- Adds a minimal implementation of `forkchoice_updated_v3()`.
- Fixes`eth_getBlockByNumber`.

**Observations**

This PR doesn't implement the `engine_forkchoiceUpdatedV3` endpoint, It only stores the minimal data needed to pass `eth_getBlockByNumber`.

Closes #270

### CODE REVIEW

**Review by vicentevieytes — APPROVED** [review]
Looks good!

File: crates/rpc/rpc.rs [hunk 1]
```diff
@@ -208,10 +212,16 @@ pub fn map_requests(req: &RpcRequest, storage: Store) -> Result<Value, RpcErr> {
...
+            let request = ForkChoiceUpdatedV3::parse(&req.params).ok_or(RpcErr::BadParams)?;
+            Ok(
+                serde_json::to_value(fork_choice::forkchoice_updated_v3(request, storage)?)
+                    .unwrap(),
+            )
+        }
         "engine_newPayloadV3" => {
             let request = NewPayloadV3Request::parse(&req.params).ok_or(RpcErr::BadParams)?;
-            Ok(serde_json::to_value(engine::new_payload_v3(request, storage)?).unwrap())
+            Ok(serde_json::to_value(payload::new_payload_v3(request, storage)?).unwrap())
```
Comment (fmoletta) [inline crates/rpc/rpc.rs:224]: Could we return an error instead of unwrapping here?

File: crates/rpc/rpc.rs [hunk 2]
```diff
@@ -208,10 +212,16 @@ pub fn map_requests(req: &RpcRequest, storage: Store) -> Result<Value, RpcErr> {
             let request = CallRequest::parse(&req.params).ok_or(RpcErr::BadParams)?;
             transaction::call(&request, storage)
         }
-        "engine_forkchoiceUpdatedV3" => engine::forkchoice_updated_v3(),
+        "engine_forkchoiceUpdatedV3" => {
+            let request = ForkChoiceUpdatedV3::parse(&req.params).ok_or(RpcErr::BadParams)?;
+            Ok(
+                serde_json::to_value(fork_choice::forkchoice_updated_v3(request, storage)?)
+                    .unwrap(),
```
[the remark this answers is not in the document]
Comment (avilagaston9) [reply crates/rpc/rpc.rs]: Totally!

File: crates/rpc/rpc.rs (hunk 1 above)
Comment (avilagaston9) [reply crates/rpc/rpc.rs]: Done!

File: crates/rpc/engine/fork_choice.rs [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+pub fn forkchoice_updated_v3(
+    request: ForkChoiceUpdatedV3,
+    storage: Store,
+) -> Result<Value, RpcErr> {
+    // Just a minimal implementation to pass rpc-compat Hive tests.
+    // TODO (#50): Implement `engine_forkchoiceUpdatedV3`
+    let safe = storage.get_block_number(request.fork_choice_state.safe_block_hash);
+    let finalized = storage.get_block_number(request.fork_choice_state.finalized_block_hash);
+
+    // Check if we already have the blocks stored.
```
Comment (mpaulucci) [inline crates/rpc/engine/fork_choice.rs:38]: no need for this check, you might get multiple updates that have the same safe/finalized block. You don't need to return an error here.

Comment (avilagaston9) [reply crates/rpc/engine/fork_choice.rs:38]: Hmmm, in this step I'm actually checking that we have those blocks stored beforehand, rather than if we have already marked them as safe/finalized. But maybe I didn't fully understand what you meant.

Comment (mpaulucci) [reply crates/rpc/engine/fork_choice.rs:38]: Ahh, my bad then.

**Review by mpaulucci — APPROVED** [review]
