### PR TITLE
fix: handle SIGINT (ctrlc) signal

### LINKED ISSUE #416: The CLI seems to ignore SIGINT
Pressing `^c` in a terminal running the `ethereum_rust` CLI seems to do nothing.
Surely it should cause an orderly shutdown of the service.

### PR DESCRIPTION
**Pull request by fkrause98**
**Motivation**

For dev purposes, and simply running and stoping the server, it's useful to handle the SIGINT signal,
which is generated by Ctrl-c

**Description**

- Simply add a tokio select statement which will wait for the event to happen.

Closes #416

### CODE REVIEW

File: cmd/ethereum_rust/ethereum_rust.rs [hunk 1]
```diff
@@ -111,17 +113,31 @@ async fn main() {
         node_id: local_node_id,
     };
 
+    // TODO: Check every module starts properly.
+    let tracer = TaskTracker::new();
```
Comment (Oppen) [inline cmd/ethereum_rust/ethereum_rust.rs:117]: I think this should be called `tracker` rather than `tracer`.

File: cmd/ethereum_rust/ethereum_rust.rs [hunk 2]
```diff
@@ -111,17 +113,31 @@ async fn main() {
         node_id: local_node_id,
     };
 
+    // TODO: Check every module starts properly.
```
Comment (Oppen) [inline cmd/ethereum_rust/ethereum_rust.rs:116]: Is this about other modules also tracking their tasks or a different thing? How does the tracker propagate, given it's not passed as an argument?

File: cmd/ethereum_rust/ethereum_rust.rs [hunk 3]
```diff
@@ -111,17 +113,31 @@ async fn main() {
...
+        ethereum_rust_net::start_network(udp_socket_addr, tcp_socket_addr, bootnodes, signer)
+            .into_future();
+
+    tracer.spawn(rpc_api);
+    tracer.spawn(networking);
+
+    tokio::select! {
+        _ = tokio::signal::ctrl_c() => {
+            info!("Server shut down started...");
+            tokio::time::sleep(Duration::from_secs(10)).await;
```
Comment (mpaulucci) [inline cmd/ethereum_rust/ethereum_rust.rs:136]: 10 seconds seems to much, I think 1 should be enough

File: cmd/ethereum_rust/ethereum_rust.rs (hunk 2 above)
Comment (fkrause98) [reply cmd/ethereum_rust/ethereum_rust.rs:116]: The tracker now only spawns the workers but does not check they start properly, maybe each module/process should return if they could start or not and give them a couple of retries, maybe this should be an issue, wdy @mpaulucci ?

File: cmd/ethereum_rust/ethereum_rust.rs (hunk 3 above)
Comment (fkrause98) [reply cmd/ethereum_rust/ethereum_rust.rs:136]: Done!

File: cmd/ethereum_rust/ethereum_rust.rs (hunk 2 above)
Comment (Oppen) [reply cmd/ethereum_rust/ethereum_rust.rs:116]: I think it merits an issue to track that down, yes.

**Review by mpaulucci — APPROVED** [review]
