### PR TITLE
fix: make `eth_getTransactionByHash` hive tests pass

### LINKED ISSUE #275: Hive Testing: `eth_getTransactionByHash`
- [ ]   get-access-list
- [ ]   get-blob-tx
- [ ]   get-dynamic-fee
- [ ]   get-empty-tx
- [ ]   get-legacy-create
- [ ]   get-legacy-input
- [ ]   get-legacy-tx
- [ ]   get-notfound-tx

### PR DESCRIPTION
**Pull request by avilagaston9**
**Motivation**

We are currently returning `null` responses to any request on the `eth_getTransactionByHash` endpoint during Hive tests.

**Description**
- When adding a new block to the chain, calls `storage.add_transaction_location()` for each transaction in the block.
- Uses `encode_canonical_to_vec()` to avoid the RLP header when calculating transaction hashes.
- Formats the response to match the expected output by Hive.
- Moves all transaction requests to the transaction rpc module.

Closes #275

### CODE REVIEW

File: crates/rpc/eth/block.rs [hunk 1]
```diff
@@ -400,7 +400,13 @@ pub fn get_transaction_by_hash(
             Some(transaction) => transaction,
             _ => return Ok(Value::Null),
         };
-
+    let (block_number, index) = storage
+        .get_transaction_location(request.transaction_hash)
+        .unwrap()
+        .unwrap();
```
Comment (ElFantasma) [inline crates/rpc/eth/block.rs:406]: It would be better to use `?` for the Result and match the Option to prevent failing on None case (like the rest of the rpc methods)

File: crates/rpc/eth/block.rs [hunk 2]
```diff
@@ -400,7 +400,13 @@ pub fn get_transaction_by_hash(
...
+    let block_header = storage.get_block_header(block_number).unwrap().unwrap();
```
Comment (ElFantasma) [inline crates/rpc/eth/block.rs:407]: Same as before... we could improve this instead of using `.unwrap().unwrap()`

**Review by ElFantasma — COMMENTED** [review]
Looks good, except for a minor improvement in error handling

File: crates/rpc/eth/block.rs (hunk 2 above)
Comment (avilagaston9) [reply crates/rpc/eth/block.rs:407]: Sorry about this. I actually meant to create a draft PR. I will clean it up and mark it as ready for review asap.

File: crates/rpc/eth/transaction.rs [hunk 3]
```diff
@@ -67,3 +181,194 @@ pub fn call(request: &CallRequest, storage: Store) -> Result<Value, RpcErr> {
...
+    let tx = RpcTransaction::build(
+        tx.clone(),
+        block_number,
+        request.block,
+        request.transaction_index,
+    );
+    serde_json::to_value(tx).map_err(|_| RpcErr::Internal)
+}
+
+pub fn get_transaction_by_hash(
```
Comment (avilagaston9) [inline crates/rpc/eth/transaction.rs:247]: This one was modified by this PR.

**Review by ElFantasma — APPROVED** [review]
