### PR TITLE
fix: `ethBlockByHash` endpoint

### LINKED ISSUE #269: Hive Testing: `eth_getBlockByHash`
- [x]   get-block-by-empty-hash
- [ ]   get-block-by-hash
- [x]   get-block-by-notfound-hash

### PR DESCRIPTION
**Pull request by avilagaston9**
**Motivation**

We are currently not matching the expected response from Hive on the `eth_getBlockByHash` endpoint.

**Description**

- Moves `BlockSerializable` to the RPC module.
- Renames `BlockSerializable` to `RpcBlock`.
- Creates `FullBlockBody` which holds `RpcTransaction` instead of `Transaction` to match the Hive expected output.
- Adds logic to calculate `TotalDifficulty` of blocks.

**Observations**

#307 was created to remove `TotalDifficulty` calculation logic added by this PR. This is because this field it is not being used since the merge, but it is still required to pass Hive tests.

Closes #269

### CODE REVIEW

File: crates/core/types/block.rs [hunk 1]
```diff
@@ -430,67 +428,14 @@ fn calc_excess_blob_gas(parent_header: &BlockHeader) -> u64 {
     }
 }
 
-#[allow(unused)]
```
Comment (mpaulucci) [inline crates/core/types/block.rs:433]: great refactor!

**Review by mpaulucci — APPROVED** [review]

**Review by fmoletta — APPROVED** [review]
🚀
